{
 "title": "count incoming",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Incoming Bytes (By country)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "  from(bucket: \"db\")\n  |> range(start: -99d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"incoming\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_count\" or r[\"_field\"] == \"location\")"
    }
   ]
  },
  {
   "title": "Incoming Bytes (By AS)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "  from(bucket: \"db\")\n  |> range(start: -99d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"incoming\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_count\" or r[\"_field\"] == \"AS\")"
    }
   ]
  },
  {
   "title": "Outgoing Bytes (By country)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "  from(bucket: \"db\")\n  |> range(start: -99d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"outgoing\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_count\" or r[\"_field\"] == \"location\")"
    }
   ]
  },
  {
   "title": "Outgoing Bytes (By AS)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "  from(bucket: \"db\")\n  |> range(start: -99d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"outgoing\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_count\" or r[\"_field\"] == \"AS\")"
    }
   ]
  }
 ]
}